### PR TITLE
Remove ember-fetch/mixins/adapter-fetch ember-fetch/ajax, drop node 8

### PR DESCRIPTION
**Pull request by stefanpenner**
ember-fetch provides alot of additional functionality, that functionality comes at several costs:

* size
* complexity / maintenance

I would like us to deprecate, and stop providing these functionality. This functionality is:

* ember-fetch/ajax: as jQuery is not longer supported, users should use fetch API’s
* ember-fetch/errors: we recommend folks use HTTP status codes directly
* ember-fetch/mixins/data: ember-data no longer needs this, it uses the fetch module provided by this add-on directly.

It allow users to utilize these features, we can point them to the 7.x branch, which we can maintain for a time. If users really want some of these features, other addons can be created, but having a kitchen sink of stuff here is unfortunately
For users who want these features, they can use [7.x branch](https://github.com/ember-cli/ember-fetch/tree/v7.x)

- [x] update readme
- [x] https://github.com/ember-cli/ember-fetch/tree/v7.x
- [ ] ????
- [x] consensus

### CODE REVIEW

**Comment by nlfurniss** [comment]
One issue with removing the `utils` is that consuming apps then have to create all that logic themselves when making one-off `fetch` calls

**Comment by stefanpenner** [comment]
@nlfurniss which are the ones that you find very useful for apps? I’m open to keeping stuff around, if it really provides value. :)

**Comment by nlfurniss** [comment]
```
ember-fetch/utils/determine-body-promise
ember-fetch/utils/mung-options-for-fetch
ember-fetch/utils/serialize-query-params
```

I would argue that `serialize-query-params` is the least necessary, though it is convenient not to need to dupe this logic across multiple apps.

`determine-body-promise` is the most useful, as it makes dealing with the response very easy.

**Comment by stefanpenner** [comment]
@nlfurniss in your opinion does it make sense for those utilities to be in this repo, or as their own dependency?

**Comment by xg-wang** [comment]
## Ajax
Those 3 util functions are helpful for existing Ajax style requests, so their existence depends on the migration path we recommend for people using Ajax.
I think we should use https://github.com/ember-cli/ember-cli-version-checker#hassingleimplementation, with existing check added in https://github.com/ember-cli/ember-fetch/pull/292 it should be okay for other addons list `ember-fetch` as dependency, so if people find direct `fetch` isn't enough they can create their own wrapper.
Related: https://github.com/ember-cli/ember-fetch/issues/398 https://github.com/ember-cli/ember-fetch/issues/222

## Error
I think they are handy, if you feel strongly about it not being a pure polyfill I'm okay removing it.

## ember-data
+1 to removal as the deprecation has been added. However we need to patch the old major to fix https://github.com/ember-cli/ember-fetch/issues/391
My first try was blocked at https://github.com/pzuraq/ember-compatibility-helpers/pull/42, maybe I can do what runspired suggested to build a debug macro. But anyway that's not against removing it.

## Only provide fetch module
Have you looked at related proposal to not even have a fetch module? https://github.com/ember-cli/ember-fetch/issues/330

**Comment by stefanpenner** [comment]
@nlfurniss / @xg-wang it sounds like we can split this into two steps:

* drop ember-data related mixins, as they are no longer needed for modern ember-data, but leave the utils + ajax helper. (land soon)
* explore the future of a more "pure" fetch world (explore and maybe land someday)

Thoughts?

**Comment by xg-wang** [comment]
Talked offline we're going to drop mixin + bump node in v8 major bump and explore the pure fetch in the future.

**Comment by bmaehr** [comment]
@xg-wang If ajax is not supported anymore (I just installed this module because of this and I'm really annoyed about this 'We remove jquery everywhere but have no alternative for doing ajax request") then you shuild remove it from the Q&A of the README (main page of the project).

**Comment by xg-wang** [comment]
@bmaehr ah thanks for pointing out! Done in https://github.com/ember-cli/ember-fetch/pull/517

**Pull request merged**
