### PR TITLE
Add failing test for using Request in FastBoot

### PR DESCRIPTION
**Pull request by bobisjan**
This is a reproduction of #355.

### CODE REVIEW

**Comment by rwjblue** [comment]
Thank you, the failing test is very helpful!

**Comment by rwjblue** [comment]
@xg-wang - You should be able to push that commit directly to this branch (GH by default allows maintainers to push to PR branches).

**Comment by xg-wang** [comment]
@rwjblue I cannot push to `zonkyio:fastboot-request-bug`, pushed to `ember-fetch/fastboot-request-bug` but it didn't seem to update this PR. Anyway I created a new PR based on that branch.

**Comment by rwjblue** [comment]
Closing in favor of #358

**Pull request closed without merging**
