### PR TITLE
Fix fetch public/fastboot-fetch.js module definition for Fastboot

### PR DESCRIPTION
**Pull request by xg-wang**
Fix https://github.com/ember-cli/ember-fetch/issues/166, depends on https://github.com/ember-cli/ember-fetch/pull/171

In v6.2.0 `fetch/setup` was added to `public/fastboot-fetch.js` so we can setup `fetch` module with fastboot request info. However this file will be overwritten by any addon's dependency `ember-fetch` based on last-write-win. To fix this:

- Rename public/fastboot-fetch.js to public/fetch-fastboot.js to avoid
lower version ember-fetch overwrite this file.
- Overrides treeForPublic in index.js to only include public tree if top
level addon.

For example, top level addon `ember-fetch` is 6.2.1, transitive dependency is anything before 6.2.0 will result in this dist:

```
dist
├── assets
│   ├── ...
├── ember-fetch
│   ├── fastboot-fetch.js
│   └── fetch-fastboot.js
```

6.2.1 as top level addon will `manifest.vendorFiles.push('ember-fetch/fetch-fastboot.js');` so the `fastboot.js` will just be ignored.

This commit also defines fetch module with a `setupFastboot` method to set host and
protocol for every instance. This could avoid module redefinition.

### CODE REVIEW

**Comment by Turbo87** [comment]
What if ember-fetch is never the top level addon? What if it is only used as a subdep with several versions?

**Comment by xg-wang** [comment]
@Turbo87 `updateFastBootManifest` is only called on top level addons. For subdeps only `treeForVendor` has effect, and we don't calculate cache key for `vendor`

**Comment by Turbo87** [comment]
@xg-wang this PR seems to contain a lot of unrelated changes now. can you make sure to open dedicated PRs for those unrelated changes?

**Comment by xg-wang** [comment]
@Turbo87 This PR is now only relying on https://github.com/ember-cli/ember-fetch/pull/171.

**Comment by samselikoff** [comment]
#171 is merged, this good to go?

**Comment by runspired** [comment]
We may want to rethink this design a bit now that `ember-fetch` is included as a dependency by `ember-data`

**Comment by rwjblue** [comment]
Agree

**Comment by dnalagatla** [comment]
+1

**Comment by e-monson** [comment]
> We may want to rethink this design a bit now that `ember-fetch` is included as a dependency by `ember-data`

What are the implications of `ember-fetch` being included as a dependency by `ember-data`? Just wondering if it could be related to my issue (#442 )

**Pull request merged**
